
inactive-opacity = 1.0;
active-opacity = 1.0;
fading = false;


# Custom opacity for terminal
opacity-rule = [
  "90:class_g = 'kitty' && focused",
  "70:class_g = 'kitty' && !focused"
];

backend = "xrender";
vsync = true;
