#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier		super
bspc config pointer_action1			move
bspc config pointer_action2			resize_side
bspc config pointer_action3			resize_cirnoer

sleep 2
~/.config/polybar/launch.sh
sleep 2
python -m pywal -i w/bg.jpg &
picom &
ibus-daemon -rxRd
